# Generated by Django 6.0.4 on 2026-05-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoLegislativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_externo', models.CharField(max_length=255, unique=True)),
                ('origem_camara_ou_senado', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=255)),
                ('ano', models.CharField(max_length=255)),
                ('ementa', models.TextField()),
                ('tipo_proposicao', models.CharField(max_length=255)),
                ('status_atual', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TermoMonitorado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra_chave', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
