# Generated by Django 6.0.4 on 2026-05-31 20:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Processos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='termomonitorado',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='termos_monitorados', to=settings.AUTH_USER_MODEL),
        ),
    ]
