# Generated by Django 6.0.4 on 2026-05-31 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Processos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processolegislativo',
            name='apreciacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processolegislativo',
            name='autor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processolegislativo',
            name='casa_iniciadora',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processolegislativo',
            name='dados_extra_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processolegislativo',
            name='data_apresentacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processolegislativo',
            name='data_status',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processolegislativo',
            name='descricao_identificacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processolegislativo',
            name='descricao_situacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processolegislativo',
            name='descricao_tipo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processolegislativo',
            name='descricao_tramitacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processolegislativo',
            name='despacho',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processolegislativo',
            name='detalhes_atualizados_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processolegislativo',
            name='ementa_detalhada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processolegislativo',
            name='indexacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processolegislativo',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processolegislativo',
            name='orgao_atual',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processolegislativo',
            name='regime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processolegislativo',
            name='tramitacao_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processolegislativo',
            name='uri_ultimo_relator',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='processolegislativo',
            name='url_autores',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='processolegislativo',
            name='url_detalhe',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='processolegislativo',
            name='url_inteiro_teor',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='processolegislativo',
            name='url_orgao_atual',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
