# Generated by Django 6.0.4 on 2026-06-20 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Processos', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_evento', models.DateTimeField()),
                ('descricao', models.TextField()),
                ('comissao_atual', models.CharField(blank=True, max_length=255, null=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='Processos.processolegislativo')),
            ],
        ),
    ]
