# Generated by Django 6.0.4 on 2026-06-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Processos', '0003_movimentacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='termomonitorado',
            name='processos',
            field=models.ManyToManyField(blank=True, related_name='termos_monitorados', to='Processos.processolegislativo'),
        ),
    ]
