# Generated by Django 6.0.4 on 2026-05-31 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Processos', '0003_processolegislativo_apreciacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processolegislativo',
            name='id_externo',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='processolegislativo',
            constraint=models.UniqueConstraint(fields=('id_externo', 'origem_camara_ou_senado'), name='unique_id_externo_origem'),
        ),
    ]
