# Generated by Django 6.0.4 on 2026-06-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Processos', '0004_alter_processolegislativo_id_externo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processolegislativo',
            name='apelido',
            field=models.CharField(blank=True, help_text='Nome popular da matéria', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='processolegislativo',
            name='casa_identificadora',
            field=models.CharField(blank=True, help_text='SF, CN, CD', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='processolegislativo',
            name='id_processo_senado',
            field=models.CharField(blank=True, help_text='ID do processo na nova API do Senado', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='processolegislativo',
            name='norma_gerada',
            field=models.CharField(blank=True, help_text='Lei gerada após aprovação', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processolegislativo',
            name='objetivo',
            field=models.CharField(blank=True, help_text='Revisora, Iniciadora', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processolegislativo',
            name='tipo_conteudo',
            field=models.CharField(blank=True, help_text='Ex: Norma Geral, Veto Constitucional', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processolegislativo',
            name='tipo_documento',
            field=models.CharField(blank=True, help_text='Ex: Medida Provisória, Projeto de Decreto Legislativo', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processolegislativo',
            name='tramitando',
            field=models.BooleanField(default=None, help_text='Se o processo está em tramitação', null=True),
        ),
    ]
