# Generated by Django 6.0.4 on 2026-07-01 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Processos', '0004_termomonitorado_processos'),
        ('Processos', '0005_processolegislativo_apelido_and_more'),
    ]

    operations = [
    ]
