# Generated by Django 6.0.4 on 2026-07-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Processos', '0006_merge_20260701_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='processolegislativo',
            name='estimativa_dias_conclusao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processolegislativo',
            name='porcentagem_conclusao',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
