# Generated by Django 6.0.4 on 2026-07-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Processos', '0007_processolegislativo_estimativa_dias_conclusao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processolegislativo',
            name='sla_status_ia',
            field=models.CharField(blank=True, help_text='Status do SLA classificado pela IA (Ex: Normal, Atenção, Estagnado)', max_length=50, null=True),
        ),
    ]
